#
# Module manifest for module 'AutomationSystem'
#
# Generated by: AutomationSystem
#
# Generated on: 29/01/2020
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'AutomationSystem.psm1'
    
    # Version number of this module.
    ModuleVersion = '1.0.0'
    
    # ID used to uniquely identify this module
    GUID = '07B81320-E748-450C-8A3B-D30147C2188D'
    
    # Author of this module
    Author = 'Vishal Bhingaradiya'
    
    # Company or vendor of this module
    CompanyName = 'J2ML Infotech Pvt. Ltd.'
    
    # Copyright statement for this module
    Copyright = '(c) 2020 J2ML Infotech Pvt. Ltd. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'PowerShell module to read the XML data and writes the data into the database to respective tables. 
        Handling the process of the XMLs to save data into the database using below 2 different methods.
            1). Using DataTable 
            2). Query Statement. 
        You can use with the updating IsDataTable flag under the Resources in config.json.
        Default is $true. If $false, XMLs will processing with the query statements and query statements is much faster than processing with the DataTables.
    '
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()
    
    # Functions to export from this module
    FunctionsToExport = '*'
    
    # Cmdlets to export from this module
    CmdletsToExport = '*'
    
    # Variables to export from this module
    VariablesToExport = '*'
    
    # Aliases to export from this module
    AliasesToExport = '*'
    
    # DSC resources to export from this module
    # DscResourcesToExport = @()
    
    # List of all modules packaged with this module
    # ModuleList = @()
    
    # List of all files packaged with this module
    # FileList = @()
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()
    
            # A URL to the license for this module.
            # LicenseUri = ''
    
            # A URL to the main website for this project.
            # ProjectUri = ''
    
            # A URL to an icon representing this module.
            # IconUri = ''
    
            # ReleaseNotes of this module
            # ReleaseNotes = ''
    
        } # End of PSData hashtable
    
    } # End of PrivateData hashtable
    
    # HelpInfo URI of this module
    # HelpInfoURI = ''
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
    
    }
    
    